# Generated by Django 5.2.6 on 2025-09-04 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_bundle_alter_category_options_remove_product_sku_and_more'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinventory',
            old_name='last_updated',
            new_name='Last_Updated',
        ),
        migrations.RenameField(
            model_name='warehouse',
            old_name='location',
            new_name='Location',
        ),
        migrations.RenameField(
            model_name='warehouse',
            old_name='name',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='maximum_quantity',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='minimum_quantity',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='id',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='Warehouse_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product'),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='status',
            field=models.CharField(default='in_stock', max_length=50),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='status',
            field=models.CharField(default='active', max_length=50),
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('Transaction_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Quantity', models.IntegerField()),
                ('Type', models.CharField(max_length=50)),
                ('Reference_Type', models.CharField(max_length=50)),
                ('Reference_ID', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse')),
            ],
        ),
        migrations.AddField(
            model_name='productinventory',
            name='Maximum_Quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productinventory',
            name='Minimum_Quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productinventory',
            name='Quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
